### ISSUE TITLE
project_test.mjs failing

### ISSUE THREAD

**Issue by alsiu7** [miahuynhh/footnote#72]
Summary: (Bug)
Provided tests are running into failures.

Component:
Test suite

Version:
Beta release

Device, OS, Browser:
Surface 7, Windows 10, Chrome

Description:
I am getting the following error when running `npm test` in the backend directory (as well as `npm run test` in root):
```
 Exception during run: file:///C:/Footnote/footnote/footnote-backend/test/project_test.mjs:4
import {getProjects, createProject, addUrl, deleteProject} from '../routes/api/projects.js';
                                    ^^^^^^
SyntaxError: Named export 'addUrl' not found. The requested module '../routes/api/projects.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../routes/api/projects.js';
const {getProjects, createProject, addUrl, deleteProject} = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:177:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:260:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async formattedImport (C:\Footnote\footnote\footnote-backend\node_modules\mocha\lib\nodejs\esm-utils.js:9:14)
    at async exports.loadFilesAsync (C:\Footnote\footnote\footnote-backend\node_modules\mocha\lib\nodejs\esm-utils.js:100:20)
    at async singleRun (C:\Footnote\footnote\footnote-backend\node_modules\mocha\lib\cli\run-helpers.js:162:3)
    at async exports.handler (C:\Footnote\footnote\footnote-backend\node_modules\mocha\lib\cli\run.js:375:5)
```

**Comment by CatherineXJJin** [comment]
It looks like the error is being caused by the test files not being up to date, so just update/pull the code and you should be fine.
Also a quick heads up - we haven't had a chance to create a separate testing database yet so running the tests will clear the main databases (users, projects, etc) of all data.

**Comment by miahuynhh** [comment]
Also please feel free to run the tests! Even though it clears the data - we don't have real user data yet :) Just be aware that you will have to create an account again and recreate your projects.
